name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.x
          - 15.x
          - 14.x
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      - run: npm test
  test-wasm:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16.x
          - 15.x
          - 14.x
          - 12.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node-version}}
      - uses: mymindstorm/setup-emsdk@v10
        with:
          version: 2.0.24
      - run: npm install --ignore-scripts
      - run: npm run build-wasm
      - run: rm -rf build
      - run: npm test
